require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry' )
require_relative( './models/continent.rb' )
require_relative( './models/country.rb' )
require_relative( './models/location.rb' )
require_relative( './models/sight_type.rb' )
require_relative( './models/sight.rb' )
also_reload('./models/*')
