DROP TABLE sights;
DROP TABLE locations;
DROP TABLE sight_types;
DROP TABLE countries;
DROP TABLE continents;

CREATE TABLE continents(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE countries(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  continent_id INT REFERENCES continents(id),
  visited BOOLEAN DEFAULT false
);

CREATE TABLE sight_types(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE locations(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  location_type VARCHAR(255),
  country_id INT REFERENCES countries(id),
  visited BOOLEAN DEFAULT false
);

CREATE TABLE sights(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  image_url VARCHAR,
  location_id INT REFERENCES locations(id),
  sight_type_id INT REFERENCES sight_types(id),
  priority INT DEFAULT 0,
  visited BOOLEAN DEFAULT false
);


INSERT INTO 'countries' ('code', 'continent_code', 'name', 'iso3', 'number', 'full_name') VALUES
  ('AS', "Afghanistan"),
  ('EU', "Åland Islands"),
  ('EU', "Albania"),
  ('AF', "Algeria"),
  ('OC', "American Samoa"),
  ('EU', "Andorra"),
  ('AF', "Angola"),
  ('NA', "Anguilla"),
  ('AN', "Antarctica"),
  ('NA', "Antigua and Barbuda"),
  ('SA', "Argentina"),
  ('AS', "Armenia"),
  ('NA', "Aruba"),
  ('OC', "Australia"),
  ('EU', "Austria"),
  ('AS', "Azerbaijan"),
  ('NA', "Bahamas"),
  ('AS', "Bahrain"),
  ('AS', "Bangladesh"),
  ('NA', "Barbados"),
  ('EU', "Belarus"),
  ('EU', "Belgium"),
  ('NA', "Belize"),
  ('AF', "Benin"),
  ('NA', "Bermuda"),
  ('AS', "Bhutan"),
  ('SA', "Bolivia"),
  ('NA', "Bonaire, Sint Eustatius and Saba"),
  ('EU', "Bosnia and Herzegovina"),
  ('AF', "Botswana"),
  ('AN', "Bouvet Island (Bouvetøya)",
  ('SA', "Brazil"),
  ('AS', "British Indian Ocean Territory (Chagos Archipelago)"),
  ('NA', "British Virgin Islands"),
  ('AS', "Brunei Darussalam"),
  ('EU', "Bulgaria"),
  ('AF', "Burkina Faso"),
  ('AF', "Burundi"),
  ('AS', "Cambodia"),
  ('AF', "Cameroon"),
  ('NA', "Canada"),
  ('AF', "Cabo Verde"),
  ('NA', "Cayman Islands"),
  ('AF', "Central African Republic"),
  ('AF', "Chad"),
  ('SA', "Chile"),
  ('AS', "China"),
  ('AS', "Christmas Island"),
  ('AS', "Cocos (Keeling) Islands"),
  ('SA', "Colombia"),
  ('AF', "Comoros"),
  ('AF', "Congo"),
  ('AF', "Congo"),
  ('OC', "Cook Islands"),
  ('NA', "Costa Rica"),
  ('AF', "Cote d'Ivoire"),
  ('EU', "Croatia"),
  ('NA', "Cuba"),
  ('NA', "Curaçao"),
  ('AS', "Cyprus"),
  ('EU', "Czechia"),
  ('EU', "Denmark"),
  ('AF', "Djibouti"),
  ('NA', "Dominica"),
  ('NA', "Dominican Republic"),
  ('SA', "Ecuador"),
  ('AF', "Egypt"),
  ('NA', "El Salvador"),
  ('AF', "Equatorial Guinea"),
  ('AF', "Eritrea"),
  ('EU', "Estonia"),
  ('AF', "Ethiopia"),
  ('EU', "Faroe Islands"),
  ('SA', "Falkland Islands (Malvinas)"),
  ('OC', "Fiji"),
  ('EU', "Finland"),
  ('EU', "France"),
  ('SA', "French Guiana"),
  ('OC', "French Polynesia"),
  ('AN', "French Southern Territories"),
  ('AF', "Gabon"),
  ('AF', "Gambia"),
  ('AS', "Georgia"),
  ('EU', "Germany"),
  ('AF', "Ghana"),
  ('EU', "Gibraltar"),
  ('EU', "Greece"),
  ('NA', "Greenland"),
  ('NA', "Grenada"),
  ('NA', "Guadeloupe"),
  ('OC', "Guam"),
  ('EU', "Guernsey"),
  ('AF', "Guinea"),
  ('AF', "Guinea-Bissau"),
  ('SA', "Guyana"),
  ('NA', "Haiti"),
  ('AN', "Heard Island and McDonald Islands"),
  ('EU', "Holy See (Vatican City State)"),
  ('NA', "Honduras"),
  ('AS', "Hong Kong"),
  ('EU', "Hungary",,
  ('EU', "Iceland"),

  
  ('AS', "India",of India"),
  ('AS', "Indonesia",of Indonesia"),
  ('AS', "Iran",epublic of Iran"),
  ('AS', "Iraq",of Iraq"),
  ('EU', "Ireland",,
  ('EU', "Isle of Man",an"),
  ('AS', "Israel",Israel"),
  ('EU', "Italy",of Italy"),
  ('NA', "Jamaica",,
  ('AS', "Japan",  ('EU', "Jersey", of Jersey"),
  ('AS', "Jordan", Kingdom of Jordan"),
  ('AS', "Kazakhstan",of Kazakhstan"),
  ('AF', "Kenya",of Kenya"),
  ('OC', "Kiribati",of Kiribati"),
  ('AS', "Korea",c People's Republic of Korea"),
  ('AS', "Korea",of Korea"),
  ('AS', "Kuwait",Kuwait"),
  ('AS', "Kyrgyz Republic",public"),
  ('AS', "Lao People's Democratic Republic",e's Democratic Republic"),
  ('EU', "Latvia",of Latvia"),
  ('AS', "Lebanon",Republic"),
  ('AF', "Lesotho",f Lesotho"),
  ('AF', "Liberia",of Liberia"),
  ('AF', "Libya",Libya"),
  ('EU', "Liechtenstein",ity of Liechtenstein"),
  ('EU', "Lithuania",of Lithuania"),
  ('EU', "Luxembourg",hy of Luxembourg"),
  ('AS', "Macao",cial Administrative Region of China"),
  ('AF', "Madagascar",of Madagascar"),
  ('AF', "Malawi",of Malawi"),
  ('AS', "Malaysia",),
  ('AS', "Maldives",of Maldives"),
  ('AF', "Mali",of Mali"),
  ('EU', "Malta",of Malta"),
  ('OC', "Marshall Islands",of the Marshall Islands"),
  ('NA', "Martinique",e"),
  ('AF', "Mauritania",epublic of Mauritania"),
  ('AF', "Mauritius",of Mauritius"),
  ('AF', "Mayotte",,
  ('NA', "Mexico",xican States"),
  ('OC', "Micronesia", States of Micronesia"),
  ('EU', "Moldova",of Moldova"),
  ('EU', "Monaco",ity of Monaco"),
  ('AS', "Mongolia",),
  ('EU', "Montenegro",o"),
  ('NA', "Montserrat",t"),
  ('AF', "Morocco",f Morocco"),
  ('AF', "Mozambique",of Mozambique"),
  ('AS', "Myanmar",of the Union of Myanmar"),
  ('AF', "Namibia",of Namibia"),
  ('OC', "Nauru",of Nauru"),
  ('AS', "Nepal",emocratic Republic of Nepal"),
  ('EU', "Netherlands",f the Netherlands"),
  ('OC', "New Caledonia",onia"),
  ('OC', "New Zealand",nd"),
  ('NA', "Nicaragua",of Nicaragua"),
  ('AF', "Niger",of Niger"),
  ('AF', "Nigeria",epublic of Nigeria"),
  ('OC', "Niue", ('OC', "Norfolk Island",sland"),
  ('EU', "North Macedonia",of North Macedonia"),
  ('OC', "Northern Mariana Islands",lth of the Northern Mariana Islands"),
  ('EU', "Norway",f Norway"),
  ('AS', "Oman", of Oman"),
  ('AS', "Pakistan",epublic of Pakistan"),
  ('OC', "Palau",of Palau"),
  ('AS', "Palestine",Palestine"),
  ('NA', "Panama",of Panama"),
  ('OC', "Papua New Guinea",nt State of Papua New Guinea"),
  ('SA', "Paraguay",of Paraguay"),
  ('SA', "Peru",of Peru"),
  ('AS', "Philippines",of the Philippines"),
  ('OC', "Pitcairn Islands",Islands"),
  ('EU', "Poland",of Poland"),
  ('EU', "Portugal",e Republic"),
  ('NA', "Puerto Rico",lth of Puerto Rico"),
  ('AS', "Qatar",Qatar"),
  ('AF', "Réunion",,
  ('EU', "Romania",,
  ('EU', "Russian Federation",ederation"),
  ('AF', "Rwanda",of Rwanda"),
  ('NA', "Saint Barthélemy",thélemy"),
  ('AF', "Saint Helena, Ascension and Tristan da Cunha",ena, Ascension and Tristan da Cunha"),
  ('NA', "Saint Kitts and Nevis",n of Saint Kitts and Nevis"),
  ('NA', "Saint Lucia",ia"),
  ('NA', "Saint Martin",tin (French part)"),
  ('NA', "Saint Pierre and Miquelon",rre and Miquelon"),
  ('NA', "Saint Vincent and the Grenadines",cent and the Grenadines"),
  ('OC', "Samoa",nt State of Samoa"),
  ('EU', "San Marino",of San Marino"),
  ('AF', "Sao Tome and Principe",c Republic of Sao Tome and Principe"),
  ('AS', "Saudi Arabia",f Saudi Arabia"),
  ('AF', "Senegal",of Senegal"),
  ('EU', "Serbia",of Serbia"),
  ('AF', "Seychelles",of Seychelles"),
  ('AF', "Sierra Leone",of Sierra Leone"),
  ('AS', "Singapore",of Singapore"),
  ('NA', "Sint Maarten (Dutch part)",ten (Dutch part)"),
  ('EU', "Slovakia (Slovak Republic)",(Slovak Republic)"),
  ('EU', "Slovenia",of Slovenia"),
  ('OC', "Solomon Islands",slands"),
  ('AF', "Somalia",epublic of Somalia"),
  ('AF', "South Africa",of South Africa"),
  ('AN', "South Georgia and the South Sandwich Islands",rgia and the South Sandwich Islands"),
  ('AF', "South Sudan",of South Sudan"),
  ('EU', "Spain",f Spain"),
  ('AS', "Sri Lanka",c Socialist Republic of Sri Lanka"),
  ('AF', "Sudan",of Sudan"),
  ('SA', "Suriname",of Suriname"),
  ('EU', "Svalbard & Jan Mayen Islands",& Jan Mayen Islands"),
  ('AF', "Eswatini",f Eswatini"),
  ('EU', "Sweden",f Sweden"),
  ('EU', "Switzerland",federation"),
  ('AS', "Syrian Arab Republic",ab Republic"),
  ('AS', "Taiwan",rovince of China"),
  ('AS', "Tajikistan",of Tajikistan"),
  ('AF', "Tanzania",public of Tanzania"),
  ('AS', "Thailand",f Thailand"),
  ('AS', "Timor-Leste",c Republic of Timor-Leste"),
  ('AF', "Togo",Republic"),
  ('OC', "Tokelau",,
  ('OC', "Tonga",f Tonga"),
  ('NA', "Trinidad and Tobago",of Trinidad and Tobago"),
  ('AF', "Tunisia",Republic"),
  ('AS', "Turkey",of Turkey"),
  ('AS', "Turkmenistan",tan"),
  ('NA', "Turks and Caicos Islands", Caicos Islands"),
  ('OC', "Tuvalu",
  ('AF', "Uganda",of Uganda"),
  ('EU', "Ukraine",,
  ('AS', "United Arab Emirates",ab Emirates"),
  ('EU', "United Kingdom of Great Britain and Northern Ireland",ngdom of Great Britain & Northern Ireland"),
  ('NA', "United States of America",ates of America"),
  ('OC', "United States Minor Outlying Islands",ates Minor Outlying Islands"),
  ('NA', "United States Virgin Islands"),
  ('SA', "Uruguay"),
  ('AS', "Uzbekistan"),
  ('OC', "Vanuatu"),
  ('SA', "Venezuela"),
  ('AS', "Vietnam"),
  ('OC', "Wallis and Futuna"),
  ('AF', "Western Sahara"),
  ('AS', "Yemen"),
  ('AF', "Zimbabwe");
